language: python

python:
  - "3.6"

# Setup anaconda
before_install:
  - sudo apt-get update
  - sudo apt-get install libnetcdf-dev nco
  - wget http://repo.continuum.io/miniconda/Miniconda3-3.16.0-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

# Make Conda environment and install packages
install: 
  - conda create --yes --name=test python=$TRAVIS_PYTHON_VERSION matplotlib basemap pandas numpy netcdf4 xarray pynco pytest -c conda-forge
  - source activate test
  - python setup.py install

# command to run tests
script:
  - rasm_post_process -h
