language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"

before_install:
  - sudo apt-get update
  - sudo apt-get install libnetcdf-dev nco

install:
  # Get anaconda
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.3" ]]; then
      wget http://repo.continuum.io/anaconda3/Anaconda3-2.1.0-Linux-x86_64.sh -O anaconda.sh;
    else
      wget http://09c8d0b2229f813c1b93-c95ac804525aac4b6dba79b00b39d1d3.r79.cf1.rackcdn.com/Anaconda-2.1.0-Linux-x86_64.sh -O anaconda.sh;
    fi
  - bash anaconda.sh -b -p $HOME/anaconda
  - export PATH="$HOME/anaconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Make Conda test environment
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment
  - conda install basemap
  - pip install xray
  - pip install nco
  - python setup.py install

# command to run tests
script:
  - rasm_post_process -h
  - py.test
